### ISSUE TITLE
[Bug]: `-c` flag not working in `read-nexus`

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/pynxtools#222]
### What happened?

When passing the `-c` flag in read_nexus, there is no output to the command line.

**Comment by lukaspie** [comment]
@sanbrock maybe you can just share the changes you made during the workshop to get it to work?

**Comment by sanbrock** [comment]
I actually used an old version from Aug 31, 2023:
de1cc043e250933173c685f242ac7322845eeac0
with nexus definitions of
81c3229100a9a8b1be4085cf16a65b279975757d

**Comment by lukaspie** [comment]
I think the problem is related to which shell you are using.

In git bash, if I pass `read_nexus -c /NXarpes/ENTRY/title` and print the concept within the `HandleNexus` class, actually the following path is passed as the concept to the `HandleNexus.process_nexus_master_file`method:
```
C:/Users/pielsticker/AppData/Local/Programs/Git/NXarpes/ENTRY/title
```
Somehow, git bash concatenates the shell path with `/NXarpes/ENTRY/title`.

Whereas if I use the vscode terminal (i.e., powershell), printing of the concept yields:
```
/NXarpes/ENTRY/title
```
and the output is correct: `INFO: entry/title`.

**Comment by lukaspie** [comment]
We could get rid of the leading `/` in `/NXarpes/ENTRY/title` and slightly modify the function that picks up the concept. That way we would be shell-independant. What do you think @sanbrock @sherjeelshabih?

**Comment by sherjeelshabih** [comment]
> We could get rid of the leading `/` in `/NXarpes/ENTRY/title` and slightly modify the function that picks up the concept. That way we would be shell-independant. What do you think @sanbrock @sherjeelshabih?

We might have to change the idea of a NeXus concept path everywhere in the code then. Otherwise, users will be confused. 

We can also try setting this ENV variable in our Python code if we are on Windows:
`MSYS_NO_PATHCONV=1`

I found this [here](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line#34386471:~:text=There%20is%20a%20way%20to%20suppress%20the%20path%20translation%20by%20setting%20MSYS_NO_PATHCONV%3D1%20in%20Windows%20Git%20MSys%20or%20MSYS2_ARG_CONV_EXCL%3D%22*%22%20in%20MSYS2.).
